/**
 * PLAIN FRAMEWORK ( https://github.com/viticm/plainframework )
 * $Id config.h
 * @link https://github.com/viticm/plainframework for the canonical source repository
 * @copyright Copyright (c) 2014- viticm( viticm.ti@gmail.com )
 * @license
 * @user viticm<viticm.ti@gmail.com>
 * @date 2014/06/23 11:22
 * @uses the net packet module id config file
 */
#ifndef COMMON_DEFINE_NET_PACKET_ID_CONFIG_H_
#define COMMON_DEFINE_NET_PACKET_ID_CONFIG_H_

#include "common/define/net/packet/config.h"

#define APPLICATION_DEFINE_NET_PACKET_ID_NAMESPACE_START \
  namespace common { \
  namespace define { \
  namespace net { \
  namespace packet { \
  namespace id {
#define APPLICATION_DEFINE_NET_PACKET_ID_NAMESPACE_END } } } } }

/*pakcetid {*/  //网络包ID的范围定义
#define PACKETID_INVALID -1

//包ID范围为宏的 MIN + 1 --- MAX - 1
//MAX = MIN + LENGTH + 2
/*gateway login { */
#define GATEWAYLOGIN_PACKETID_MIN 5 //前1--5为服务器直接公用的包
#define GATEWAYLOGIN_PACKETID_MAX (GATEWAYLOGIN_PACKETID_MIN + 10 + 2)
#define GATEWAY_TOLOGIN_PACKETID_MIN (GATEWAYLOGIN_PACKETID_MAX - 1)
#define GATEWAY_TOLOGIN_PACKETID_MAX (GATEWAY_TOLOGIN_PACKETID_MIN + 58 + 2)
#define LOGIN_TOGATEWAY_PACKETID_MIN (GATEWAY_TOLOGIN_PACKETID_MAX - 1)
#define LOGIN_TOGATEWAY_PACKETID_MAX (LOGIN_TOGATEWAY_PACKETID_MIN + 58 + 2)
/*gateway login }*/

/*client login {*/
#define CLIENTLOGIN_PACKETID_MIN (LOGIN_TOGATEWAY_PACKETID_MAX - 1)
#define CLIENTLOGIN_PACKETID_MAX (CLIENTLOGIN_PACKETID_MIN + 58 + 2)
#define LOGIN_TOCLIENT_PACKETID_MIN (CLIENTLOGIN_PACKETID_MAX - 1)
#define LOGIN_TOCLIENT_PACKETID_MAX (LOGIN_TOCLIENT_PACKETID_MIN + 58 + 2)
#define CLIENT_TOLOGIN_PACKETID_MIN (LOGIN_TOCLIENT_PACKETID_MAX - 1)
#define CLIENT_TOLOGIN_PACKETID_MAX (CLIENT_TOLOGIN_PACKETID_MIN + 58 + 2)
/*login client }*/

/*login center {*/
#define LOGINCENTER_PACKETID_MIN (CLIENT_TOLOGIN_PACKETID_MAX - 1)
#define LOGINCENTER_PACKETID_MAX (LOGINCENTER_PACKETID_MIN + 58 + 2)
#define LOGIN_TOCENTER_PACKETID_MIN (LOGINCENTER_PACKETID_MAX - 1)
#define LOGIN_TOCENTER_PACKETID_MAX (LOGIN_TOCENTER_PACKETID_MIN + 58 + 2)
#define CENTER_TOLOGIN_PACKETID_MIN (LOGIN_TOCENTER_PACKETID_MAX - 1)
#define CENTER_TOLOGIN_PACKETID_MAX (CENTER_TOLOGIN_PACKETID_MIN + 58 + 2)
/*login center }*/

/*server center {*/
#define SERVERCENTER_PACKETID_MIN (CENTER_TOLOGIN_PACKETID_MAX - 1)
#define SERVERCENTER_PACKETID_MAX (SERVERCENTER_PACKETID_MIN + 58 + 2)
#define CENTER_TOSERVER_PACKETID_MIN (SERVERCENTER_PACKETID_MAX - 1)
#define CENTER_TOSERVER_PACKETID_MAX (CENTER_TOSERVER_PACKETID_MIN + 58 + 2)
#define SERVER_TOCENTER_PACKETID_MIN (CENTER_TOSERVER_PACKETID_MAX - 1)
#define SERVER_TOCENTER_PACKETID_MAX (SERVER_TOCENTER_PACKETID_MIN + 58 + 2)
/*server center }*/

/*client server {*/
#define CLIENTSERVER_PACKETID_MIN (SERVER_TOCENTER_PACKETID_MAX - 1)
#define CLIENTSERVER_PACKETID_MAX (CLIENTSERVER_PACKETID_MIN + 100 + 2)
#define CLIENT_TOSERVER_PACKETID_MIN (CLIENTSERVER_PACKETID_MAX - 1)
#define CLIENT_TOSERVER_PACKETID_MAX (CLIENT_TOSERVER_PACKETID_MIN + 1000 + 2)
#define SERVER_TOCLIENT_PACKETID_MIN (CLIENT_TOSERVER_PACKETID_MAX - 1)
#define SERVER_TOCLIENT_PACKETID_MAX (SERVER_TOCLIENT_PACKETID_MIN + 1000 + 2)
/*client server }*/

/* } packetid*/


#endif //COMMON_DEFINE_NET_PACKET_ID_CONFIG_H_
